spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/nexo
    username: nexo
    password: nexo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true